# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'snake_pch' do

pod "AFNetworking"
pod "Masonry"

pod 'ZXConvenientCode', :path => '../ZXConvenientCode/'

pod 'ZXUIKit', :path => '../ZXUIKit_iOS'

# pod 'ZXSugarCode', :path => '../ZXSugarCode'

end

target 'snake_pchTests' do

end

target 'snake_pchUITests' do

end

