# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'snake_pch' do

pod "AFNetworking"

pod 'ZXConvenientCode', :path => '../ZXConvenientCode/'

# pod 'ZXSugarCode', :path => '../ZXSugarCode'

end

target 'snake_pchTests' do

end

target 'snake_pchUITests' do

end

